#ifndef _INC_SEETA_FACE_DETECTOR_V6_
#define _INC_SEETA_FACE_DETECTOR_V6_

#define SEETA_FACE_DETECTOR_MAJOR_VERSION 6
#define SEETA_FACE_DETECTOR_MINOR_VERSION 0
#define SEETA_FACE_DETECTOR_SINOR_VERSION 0

#define SEETA_FACE_DETECTOR_LIBRARY_NAME "SeetaFaceDetector"

#define SEETA_FACE_DETECTOR_NAMESPACE_VERSION v6

#endif  // _INC_SEETA_FACE_DETECTOR_V6_
