#pragma once

#define SEETA_FACE_LANDMARKER_MAJOR_VERSION 6
#define SEETA_FACE_LANDMARKER_MINOR_VERSION 0
#define SEETA_FACE_LANDMARKER_SINOR_VERSION 0

#define SEETA_FACE_LANDMARKER_LIBRARY_NAME "SeetaFaceLandmarker"

#define SEETA_FACE_LANDMARKER_NAMESPACE_VERSION v6
