#ifndef _INC_SEETA_MASK_DETECTOR_V2_
#define _INC_SEETA_MASK_DETECTOR_V2_

#define SEETA_POSE_ESTIMATOR_MAJOR_VERSION 2
#define SEETA_POSE_ESTIMATOR_MINOR_VERSION 0
#define SEETA_POSE_ESTIMATOR_SINOR_VERSION 0

#define SEETA_POSE_ESTIMATOR_LIBRARY_NAME "SeetaMaskDetector"

#define SEETA_POSE_ESTIMATOR_NAMESPACE_VERSION v2

#endif  // _INC_SEETA_MASK_DETECTOR_V2_
