#pragma once

#define SEETA_FACE_RECOGNIZER_MAJOR_VERSION 6
#define SEETA_FACE_RECOGNIZER_MINOR_VERSION 1
#define SEETA_FACE_RECOGNIZER_SINOR_VERSION 0

#define SEETA_FACE_RECOGNIZE_LIBRARY_NAME "SeetaFaceRecognizer"

#define SEETA_FACE_RECOGNIZE_NAMESPACE_VERSION v6
